# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZXKitSwiftDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZXKitSwiftDemo
  pod 'ZXKitLogger/zxkit'
  pod 'ZXKitFPS/zxkit'
  pod 'HDPingTools/zxkit'
  pod 'ZXFileBrowser/zxkit'
  pod 'ZXUserDefaultManager/zxkit'
end
