# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DDKitSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DDKitSwift
  pod 'DDUtils/ui', '~> 5.0.0'
  pod 'DDUtils/utils', '~> 5.0.0'
  pod 'DDLoggerSwift', '~> 5.0.0'
end
